# Generated by the protocol buffer compiler. DO NOT EDIT!
"""Current Engram protocol messages."""

from google.protobuf import descriptor_pool as imported_descriptor_pool
from google.protobuf import empty_pb2 as protobuf_empty
from google.protobuf import struct_pb2 as protobuf_struct
from google.protobuf.internal import builder as imported_builder

DESCRIPTOR = imported_descriptor_pool.Default().AddSerializedFile(
    b"\n\x13engram/engram.proto\x12\x06engram\x1a\x1bgoogle/protobuf/e"
    b'mpty.proto\x1a\x1cgoogle/protobuf/struct.proto"o\n\x18Star'
    b"tConversationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x18\n\x10initial"
    b"_bot_text\x18\x02 \x01(\t\x12\x18\n\x0brandom_seed\x18\x03 \x01(\x03H\x00\x88\x01\x01B\x0e\n\x0c_ra"
    b'ndom_seed",\n\x0bChatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04tex'
    b't\x18\x02 \x01(\t"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t"4\n\x0eAddFa'
    b'ctRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0csource_label\x18\x02 \x01(\t"C\n'
    b"\x13SetPredicateRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 "
    b'\x01(\t\x12\r\n\x05value\x18\x03 \x01(\t"K\n\x13GetPredicateRequest\x12\x0f\n\x07use'
    b'r_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rdefault_value\x18\x03 \x01(\t"'
    b'"\n\x11PredicateResponse\x12\r\n\x05value\x18\x01 \x01(\t"\xe7\x01\n\x0eProposeR'
    b"equest\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0f\n\x07u"
    b"ser_id\x18\x03 \x01(\t\x12\x11\n\tnamespace\x18\x04 \x01(\t\x12\x1b\n\x13context_finge"
    b"rprint\x18\x05 \x01(\t\x12\x12\n\x05limit\x18\x06 \x01(\x05H\x00\x88\x01\x01\x122\n\x11required_met"
    b"adata\x18\x07 \x01(\x0b2\x17.google.protobuf.Struct\x12\x1d\n\x15required"
    b'_source_label\x18\x08 \x01(\tB\x08\n\x06_limit"v\n\x0eResolveRequest\x12'
    b"\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12)\n\x07outcome\x18\x02 \x01(\x0e2\x18.engram.R"
    b"egulatorOutcome\x12\x14\n\x0cstatement_id\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18"
    b'\x04 \x01(\t"\xcf\x01\n\x14LearnResponseRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\x12'
    b"\x10\n\x08response\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id"
    b"\x18\x04 \x01(\t\x12\x11\n\tnamespace\x18\x05 \x01(\t\x12\x1b\n\x13context_fingerprint"
    b"\x18\x06 \x01(\t\x12\x14\n\x0csource_label\x18\x07 \x01(\t\x12)\n\x08metadata\x18\x08 \x01(\x0b2\x17"
    b'.google.protobuf.Struct"Q\n\x15RetireResponseRequest'
    b"\x12\x14\n\x0cstatement_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x12\n\nreques"
    b't_id\x18\x03 \x01(\t"\xd9\x02\n\x16ResolveEvidenceRequest\x12\x0f\n\x07request'
    b"\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x11\n\tn"
    b"amespace\x18\x04 \x01(\t\x12\x1b\n\x13context_fingerprint\x18\x05 \x01(\t\x12)\n\x08i"
    b"dentity\x18\x06 \x01(\x0b2\x17.google.protobuf.Struct\x122\n\x11requir"
    b"ed_metadata\x18\x07 \x01(\x0b2\x17.google.protobuf.Struct\x12\x1d\n\x15re"
    b"quired_source_label\x18\x08 \x01(\t\x12'\n\x06budget\x18\t \x01(\x0b2\x17.goog"
    b"le.protobuf.Struct\x12\x1c\n\x14configured_resolvers\x18\n \x03(\t"
    b'\x12\x14\n\x0caccept_exact\x18\x0b \x01(\x08"\xaf\x01\n\x0fEvidencePackage\x12\x14\n\x0cwi'
    b"re_version\x18\x01 \x01(\r\x12(\n\x07records\x18\x02 \x03(\x0b2\x17.google.proto"
    b"buf.Struct\x12\x16\n\x0eretained_count\x18\x03 \x01(\r\x12\x15\n\romitted_co"
    b"unt\x18\x04 \x01(\r\x12\x11\n\ttruncated\x18\x05 \x01(\x08\x12\x1a\n\x12truncation_reaso"
    b'ns\x18\x06 \x03(\t"\xa6\x04\n\x10ResolutionResult\x12\x16\n\x0eschema_version\x18'
    b"\x01 \x01(\r\x12\x0f\n\x07outcome\x18\x02 \x01(\t\x123\n\x12selected_candidate\x18\x03 \x01"
    b"(\x0b2\x17.google.protobuf.Struct\x12$\n\x1cselected_candidat"
    b"e_available\x18\x04 \x01(\x08\x124\n\x13response_candidates\x18\x05 \x03(\x0b2\x17"
    b".google.protobuf.Struct\x12)\n\x08evidence\x18\x06 \x03(\x0b2\x17.goog"
    b"le.protobuf.Struct\x12\x12\n\nconfidence\x18\x07 \x01(\x01\x12\x1c\n\x14confid"
    b"ence_available\x18\x08 \x01(\x08\x12\x14\n\x0creason_codes\x18\t \x03(\t\x122\n\x11fr"
    b"ame_diagnostics\x18\n \x01(\x0b2\x17.google.protobuf.Struct\x121"
    b"\n\x10resolver_results\x18\x0b \x03(\x0b2\x17.google.protobuf.Struc"
    b"t\x12'\n\x06budget\x18\x0c \x01(\x0b2\x17.google.protobuf.Struct\x12\"\n\x1aev"
    b"idence_package_available\x18\r \x01(\x08\x121\n\x10evidence_packa"
    b"ge\x18\x0e \x01(\x0b2\x17.engram.EvidencePackage*\xf2\x01\n\x10RegulatorO"
    b"utcome\x12!\n\x1dREGULATOR_OUTCOME_UNSPECIFIED\x10\x00\x12\x1e\n\x1aREG"
    b'ULATOR_OUTCOME_ACCEPTED\x10\x01\x12&\n"REGULATOR_OUTCOME_R'
    b'EJECTED_QUALITY\x10\x02\x12&\n"REGULATOR_OUTCOME_REJECTED_'
    b"CONTEXT\x10\x03\x12$\n REGULATOR_OUTCOME_REJECTED_STALE\x10\x04\x12"
    b"%\n!REGULATOR_OUTCOME_REJECTED_POLICY\x10\x052\xf4\x06\n\rEngra"
    b"mService\x12N\n\x11StartConversation\x12 .engram.StartConv"
    b"ersationRequest\x1a\x17.google.protobuf.Struct\x124\n\x04Chat"
    b"\x12\x13.engram.ChatRequest\x1a\x17.google.protobuf.Struct\x12C"
    b"\n\x13InspectConversation\x12\x13.engram.UserRequest\x1a\x17.goo"
    b"gle.protobuf.Struct\x12B\n\x12FinishConversation\x12\x13.engr"
    b"am.UserRequest\x1a\x17.google.protobuf.Struct\x12@\n\x10StopC"
    b"onversation\x12\x13.engram.UserRequest\x1a\x17.google.protob"
    b"uf.Struct\x12:\n\x07AddFact\x12\x16.engram.AddFactRequest\x1a\x17.g"
    b"oogle.protobuf.Struct\x12F\n\x0cSetPredicate\x12\x1b.engram.S"
    b"etPredicateRequest\x1a\x19.engram.PredicateResponse\x12F\n"
    b"\x0cGetPredicate\x12\x1b.engram.GetPredicateRequest\x1a\x19.eng"
    b"ram.PredicateResponse\x12:\n\x07Propose\x12\x16.engram.Propos"
    b"eRequest\x1a\x17.google.protobuf.Struct\x12:\n\x07Resolve\x12\x16.e"
    b"ngram.ResolveRequest\x1a\x17.google.protobuf.Struct\x12F\n"
    b"\rLearnResponse\x12\x1c.engram.LearnResponseRequest\x1a\x17.g"
    b"oogle.protobuf.Struct\x12H\n\x0eRetireResponse\x12\x1d.engram"
    b".RetireResponseRequest\x1a\x17.google.protobuf.Struct\x12"
    b"<\n\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x17.google.pr"
    b"otobuf.Struct2d\n\x15EngramEvidenceService\x12K\n\x0fResolv"
    b"eEvidence\x12\x1e.engram.ResolveEvidenceRequest\x1a\x18.engr"
    b"am.ResolutionResultb\x06proto3"
)

module_globals = globals()
imported_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, module_globals)
imported_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "engram.engram_pb2", module_globals)
