# Generated by the protocol buffer compiler. DO NOT EDIT!
"""Current Engram protocol messages."""

from google.protobuf import descriptor_pool as imported_descriptor_pool
from google.protobuf import empty_pb2 as protobuf_empty
from google.protobuf import struct_pb2 as protobuf_struct
from google.protobuf.internal import builder as imported_builder

DESCRIPTOR = imported_descriptor_pool.Default().AddSerializedFile(
    b"\n\x13engram/engram.proto\x12\x06engram\x1a\x1bgoogle/protobuf/e"
    b'mpty.proto\x1a\x1cgoogle/protobuf/struct.proto"o\n\x18Star'
    b"tConversationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x18\n\x10initial"
    b"_bot_text\x18\x02 \x01(\t\x12\x18\n\x0brandom_seed\x18\x03 \x01(\x03H\x00\x88\x01\x01B\x0e\n\x0c_ra"
    b'ndom_seed"H\n\x0bChatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04tex'
    b't\x18\x02 \x01(\t\x12\x1a\n\x12conversation_token\x18\x03 \x01(\t":\n\x0bUserReque'
    b'st\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1a\n\x12conversation_token\x18\x02 \x01(\t"'
    b"4\n\x0eAddFactRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0csource_label\x18"
    b'\x02 \x01(\t"C\n\x13SetPredicateRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n'
    b'\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t"K\n\x13GetPredicateReques'
    b"t\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rdefault_valu"
    b'e\x18\x03 \x01(\t""\n\x11PredicateResponse\x12\r\n\x05value\x18\x01 \x01(\t"\xe7\x01\n\x0e'
    b"ProposeRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 "
    b"\x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x11\n\tnamespace\x18\x04 \x01(\t\x12\x1b\n\x13conte"
    b"xt_fingerprint\x18\x05 \x01(\t\x12\x12\n\x05limit\x18\x06 \x01(\x05H\x00\x88\x01\x01\x122\n\x11requ"
    b"ired_metadata\x18\x07 \x01(\x0b2\x17.google.protobuf.Struct\x12\x1d\n\x15"
    b'required_source_label\x18\x08 \x01(\tB\x08\n\x06_limit"v\n\x0eResolve'
    b"Request\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12)\n\x07outcome\x18\x02 \x01(\x0e2\x18."
    b"engram.RegulatorOutcome\x12\x14\n\x0cstatement_id\x18\x03 \x01(\t\x12\x0e\n"
    b'\x06reason\x18\x04 \x01(\t"\xcf\x01\n\x14LearnResponseRequest\x12\x0f\n\x07reques'
    b"t\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x0f\n"
    b"\x07user_id\x18\x04 \x01(\t\x12\x11\n\tnamespace\x18\x05 \x01(\t\x12\x1b\n\x13context_fin"
    b"gerprint\x18\x06 \x01(\t\x12\x14\n\x0csource_label\x18\x07 \x01(\t\x12)\n\x08metadata"
    b'\x18\x08 \x01(\x0b2\x17.google.protobuf.Struct"Q\n\x15RetireRespons'
    b"eRequest\x12\x14\n\x0cstatement_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x12"
    b'\n\nrequest_id\x18\x03 \x01(\t"H\n\x16RetireResponsesRequest\x12.\n\x07'
    b'entries\x18\x01 \x03(\x0b2\x1d.engram.RetireResponseRequest"/\n\x19'
    b'ResponsesBySupportRequest\x12\x12\n\nrecord_ids\x18\x01 \x03(\t"\xd9\x02'
    b"\n\x16ResolveEvidenceRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\x12\n\nreq"
    b"uest_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x11\n\tnamespace\x18\x04 \x01("
    b"\t\x12\x1b\n\x13context_fingerprint\x18\x05 \x01(\t\x12)\n\x08identity\x18\x06 \x01(\x0b"
    b"2\x17.google.protobuf.Struct\x122\n\x11required_metadata\x18\x07"
    b" \x01(\x0b2\x17.google.protobuf.Struct\x12\x1d\n\x15required_source"
    b"_label\x18\x08 \x01(\t\x12'\n\x06budget\x18\t \x01(\x0b2\x17.google.protobuf.S"
    b"truct\x12\x1c\n\x14configured_resolvers\x18\n \x03(\t\x12\x14\n\x0caccept_ex"
    b'act\x18\x0b \x01(\x08"\xad\x01\n\x0fEvidencePackage\x12(\n\x07records\x18\x02 \x03(\x0b2\x17'
    b".google.protobuf.Struct\x12\x16\n\x0eretained_count\x18\x03 \x01(\r\x12"
    b"\x15\n\romitted_count\x18\x04 \x01(\r\x12\x11\n\ttruncated\x18\x05 \x01(\x08\x12\x1a\n\x12tru"
    b'ncation_reasons\x18\x06 \x03(\tJ\x04\x08\x01\x10\x02R\x0cwire_version"\xa4\x04\n\x10Re'
    b"solutionResult\x12\x0f\n\x07outcome\x18\x02 \x01(\t\x123\n\x12selected_cand"
    b"idate\x18\x03 \x01(\x0b2\x17.google.protobuf.Struct\x12$\n\x1cselected"
    b"_candidate_available\x18\x04 \x01(\x08\x124\n\x13response_candidate"
    b"s\x18\x05 \x03(\x0b2\x17.google.protobuf.Struct\x12)\n\x08evidence\x18\x06 \x03"
    b"(\x0b2\x17.google.protobuf.Struct\x12\x12\n\nconfidence\x18\x07 \x01(\x01\x12"
    b"\x1c\n\x14confidence_available\x18\x08 \x01(\x08\x12\x14\n\x0creason_codes\x18\t "
    b"\x03(\t\x122\n\x11frame_diagnostics\x18\n \x01(\x0b2\x17.google.protobuf"
    b".Struct\x121\n\x10resolver_results\x18\x0b \x03(\x0b2\x17.google.proto"
    b"buf.Struct\x12'\n\x06budget\x18\x0c \x01(\x0b2\x17.google.protobuf.Str"
    b'uct\x12"\n\x1aevidence_package_available\x18\r \x01(\x08\x121\n\x10evide'
    b"nce_package\x18\x0e \x01(\x0b2\x17.engram.EvidencePackageJ\x04\x08\x01\x10\x02"
    b"R\x0eschema_version*\xf2\x01\n\x10RegulatorOutcome\x12!\n\x1dREGULAT"
    b"OR_OUTCOME_UNSPECIFIED\x10\x00\x12\x1e\n\x1aREGULATOR_OUTCOME_AC"
    b'CEPTED\x10\x01\x12&\n"REGULATOR_OUTCOME_REJECTED_QUALITY\x10\x02'
    b'\x12&\n"REGULATOR_OUTCOME_REJECTED_CONTEXT\x10\x03\x12$\n REGU'
    b"LATOR_OUTCOME_REJECTED_STALE\x10\x04\x12%\n!REGULATOR_OUTC"
    b"OME_REJECTED_POLICY\x10\x052\xda\x08\n\rEngramService\x12N\n\x11Start"
    b"Conversation\x12 .engram.StartConversationRequest\x1a\x17"
    b".google.protobuf.Struct\x124\n\x04Chat\x12\x13.engram.ChatReq"
    b"uest\x1a\x17.google.protobuf.Struct\x12C\n\x13InspectConversa"
    b"tion\x12\x13.engram.UserRequest\x1a\x17.google.protobuf.Stru"
    b"ct\x12B\n\x12FinishConversation\x12\x13.engram.UserRequest\x1a\x17."
    b"google.protobuf.Struct\x12@\n\x10StopConversation\x12\x13.eng"
    b"ram.UserRequest\x1a\x17.google.protobuf.Struct\x12:\n\x07AddF"
    b"act\x12\x16.engram.AddFactRequest\x1a\x17.google.protobuf.St"
    b"ruct\x12F\n\x0cSetPredicate\x12\x1b.engram.SetPredicateReques"
    b"t\x1a\x19.engram.PredicateResponse\x12F\n\x0cGetPredicate\x12\x1b.e"
    b"ngram.GetPredicateRequest\x1a\x19.engram.PredicateResp"
    b"onse\x12:\n\x07Propose\x12\x16.engram.ProposeRequest\x1a\x17.google"
    b".protobuf.Struct\x12:\n\x07Resolve\x12\x16.engram.ResolveRequ"
    b"est\x1a\x17.google.protobuf.Struct\x12F\n\rLearnResponse\x12\x1c."
    b"engram.LearnResponseRequest\x1a\x17.google.protobuf.St"
    b"ruct\x12H\n\x0eRetireResponse\x12\x1d.engram.RetireResponseRe"
    b"quest\x1a\x17.google.protobuf.Struct\x12J\n\x0fRetireResponse"
    b"s\x12\x1e.engram.RetireResponsesRequest\x1a\x17.google.proto"
    b"buf.Struct\x12P\n\x12ResponsesBySupport\x12!.engram.Respon"
    b"sesBySupportRequest\x1a\x17.google.protobuf.Struct\x12F\n\x12"
    b"MaintainEngagement\x12\x17.google.protobuf.Struct\x1a\x17.go"
    b"ogle.protobuf.Struct\x12<\n\tGetStatus\x12\x16.google.proto"
    b"buf.Empty\x1a\x17.google.protobuf.Struct2d\n\x15EngramEvid"
    b"enceService\x12K\n\x0fResolveEvidence\x12\x1e.engram.ResolveE"
    b"videnceRequest\x1a\x18.engram.ResolutionResultb\x06proto3"
)

module_globals = globals()
imported_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, module_globals)
imported_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "engram.engram_pb2", module_globals)
