# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
from grpc import StatusCode as grpc_StatusCode
from grpc import method_handlers_generic_handler as grpc_method_handlers_generic_handler
from grpc import unary_unary_rpc_method_handler as grpc_unary_unary_rpc_method_handler

from engram import engram_pb2 as engram_protocol
from google.protobuf import empty_pb2 as protobuf_empty
from google.protobuf import struct_pb2 as protobuf_struct


class EngramServiceStub:
    """A single Engram process owns one instance of this service and one shared
    EngramCore. Conversation context is isolated by user_id; learned knowledge
    is shared by the core.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartConversation = channel.unary_unary(
            "/engram.EngramService/StartConversation",
            request_serializer=engram_protocol.StartConversationRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.Chat = channel.unary_unary(
            "/engram.EngramService/Chat",
            request_serializer=engram_protocol.ChatRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.InspectConversation = channel.unary_unary(
            "/engram.EngramService/InspectConversation",
            request_serializer=engram_protocol.UserRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.FinishConversation = channel.unary_unary(
            "/engram.EngramService/FinishConversation",
            request_serializer=engram_protocol.UserRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.StopConversation = channel.unary_unary(
            "/engram.EngramService/StopConversation",
            request_serializer=engram_protocol.UserRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.AddFact = channel.unary_unary(
            "/engram.EngramService/AddFact",
            request_serializer=engram_protocol.AddFactRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.SetPredicate = channel.unary_unary(
            "/engram.EngramService/SetPredicate",
            request_serializer=engram_protocol.SetPredicateRequest.SerializeToString,
            response_deserializer=engram_protocol.PredicateResponse.FromString,
            **{"_registered_method": True},
        )
        self.GetPredicate = channel.unary_unary(
            "/engram.EngramService/GetPredicate",
            request_serializer=engram_protocol.GetPredicateRequest.SerializeToString,
            response_deserializer=engram_protocol.PredicateResponse.FromString,
            **{"_registered_method": True},
        )
        self.Propose = channel.unary_unary(
            "/engram.EngramService/Propose",
            request_serializer=engram_protocol.ProposeRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.Resolve = channel.unary_unary(
            "/engram.EngramService/Resolve",
            request_serializer=engram_protocol.ResolveRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.LearnResponse = channel.unary_unary(
            "/engram.EngramService/LearnResponse",
            request_serializer=engram_protocol.LearnResponseRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.RetireResponse = channel.unary_unary(
            "/engram.EngramService/RetireResponse",
            request_serializer=engram_protocol.RetireResponseRequest.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )
        self.GetStatus = channel.unary_unary(
            "/engram.EngramService/GetStatus",
            request_serializer=protobuf_empty.Empty.SerializeToString,
            response_deserializer=protobuf_struct.Struct.FromString,
            **{"_registered_method": True},
        )


class EngramServiceServicer:
    """A single Engram process owns one instance of this service and one shared
    EngramCore. Conversation context is isolated by user_id; learned knowledge
    is shared by the core.
    """

    def StartConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InspectConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FinishConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddFact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetPredicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPredicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Resolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LearnResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RetireResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EngramServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StartConversation": grpc_unary_unary_rpc_method_handler(
            servicer.StartConversation,
            request_deserializer=engram_protocol.StartConversationRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "Chat": grpc_unary_unary_rpc_method_handler(
            servicer.Chat,
            request_deserializer=engram_protocol.ChatRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "InspectConversation": grpc_unary_unary_rpc_method_handler(
            servicer.InspectConversation,
            request_deserializer=engram_protocol.UserRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "FinishConversation": grpc_unary_unary_rpc_method_handler(
            servicer.FinishConversation,
            request_deserializer=engram_protocol.UserRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "StopConversation": grpc_unary_unary_rpc_method_handler(
            servicer.StopConversation,
            request_deserializer=engram_protocol.UserRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "AddFact": grpc_unary_unary_rpc_method_handler(
            servicer.AddFact,
            request_deserializer=engram_protocol.AddFactRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "SetPredicate": grpc_unary_unary_rpc_method_handler(
            servicer.SetPredicate,
            request_deserializer=engram_protocol.SetPredicateRequest.FromString,
            response_serializer=engram_protocol.PredicateResponse.SerializeToString,
        ),
        "GetPredicate": grpc_unary_unary_rpc_method_handler(
            servicer.GetPredicate,
            request_deserializer=engram_protocol.GetPredicateRequest.FromString,
            response_serializer=engram_protocol.PredicateResponse.SerializeToString,
        ),
        "Propose": grpc_unary_unary_rpc_method_handler(
            servicer.Propose,
            request_deserializer=engram_protocol.ProposeRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "Resolve": grpc_unary_unary_rpc_method_handler(
            servicer.Resolve,
            request_deserializer=engram_protocol.ResolveRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "LearnResponse": grpc_unary_unary_rpc_method_handler(
            servicer.LearnResponse,
            request_deserializer=engram_protocol.LearnResponseRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "RetireResponse": grpc_unary_unary_rpc_method_handler(
            servicer.RetireResponse,
            request_deserializer=engram_protocol.RetireResponseRequest.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
        "GetStatus": grpc_unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=protobuf_empty.Empty.FromString,
            response_serializer=protobuf_struct.Struct.SerializeToString,
        ),
    }
    generic_handler = grpc_method_handlers_generic_handler("engram.EngramService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("engram.EngramService", rpc_method_handlers)


class EngramEvidenceServiceStub:
    """Unified resolution is an additional capability of the same Engram core."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveEvidence = channel.unary_unary(
            "/engram.EngramEvidenceService/ResolveEvidence",
            request_serializer=engram_protocol.ResolveEvidenceRequest.SerializeToString,
            response_deserializer=engram_protocol.ResolutionResult.FromString,
            **{"_registered_method": True},
        )


class EngramEvidenceServiceServicer:
    """Unified resolution is an additional capability of the same Engram core."""

    def ResolveEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EngramEvidenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ResolveEvidence": grpc_unary_unary_rpc_method_handler(
            servicer.ResolveEvidence,
            request_deserializer=engram_protocol.ResolveEvidenceRequest.FromString,
            response_serializer=engram_protocol.ResolutionResult.SerializeToString,
        ),
    }
    generic_handler = grpc_method_handlers_generic_handler("engram.EngramEvidenceService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("engram.EngramEvidenceService", rpc_method_handlers)
