"""Regenerate and normalize Engram's current protobuf transport modules."""

from ast import Assign, Call, ClassDef, Constant, Name, parse, walk
from pathlib import Path
from subprocess import CalledProcessError, run as subprocess_run
from sys import executable as sys_executable, stderr

REPOSITORY = Path(__file__).resolve().parent.parent
PROTO = REPOSITORY / "engram" / "engram.proto"
PROTOBUF_SOURCE = REPOSITORY / "engram" / "engram_pb2.py"
GRPC_SOURCE = REPOSITORY / "engram" / "engram_pb2_grpc.py"
STALE_STUB = REPOSITORY / "engram" / "engram_pb2.pyi"
DESCRIPTOR_CHUNK_BYTES = 48


def descriptor_argument(source: str) -> Constant:
    """Locate the serialized descriptor bytes in generated protobuf source."""
    tree = parse(source, filename=str(PROTOBUF_SOURCE))
    for node in walk(tree):
        if not isinstance(node, Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, Name) or target.id != "DESCRIPTOR":
            continue
        if not isinstance(node.value, Call) or len(node.value.args) != 1:
            break
        argument = node.value.args[0]
        if isinstance(argument, Constant) and isinstance(argument.value, bytes):
            return argument
        break
    raise ValueError("generated protobuf source has no serialized DESCRIPTOR bytes")


def normalize_protobuf_source() -> None:
    """Keep the descriptor and current pinned protobuf runtime surface."""
    source = PROTOBUF_SOURCE.read_text(encoding="utf-8")
    argument = descriptor_argument(source)
    value = argument.value
    chunks = [value[index : index + DESCRIPTOR_CHUNK_BYTES] for index in range(0, len(value), DESCRIPTOR_CHUNK_BYTES)]
    descriptor_lines = "\n".join(f"    {chunk!r}" for chunk in chunks)
    source = (
        "# Generated by the protocol buffer compiler. DO NOT EDIT!\n"
        '"""Current Engram protocol messages."""\n\n'
        "from google.protobuf import descriptor_pool as imported_descriptor_pool\n"
        "from google.protobuf import empty_pb2 as protobuf_empty\n"
        "from google.protobuf import struct_pb2 as protobuf_struct\n"
        "from google.protobuf.internal import builder as imported_builder\n\n"
        "DESCRIPTOR = imported_descriptor_pool.Default().AddSerializedFile(\n"
        f"{descriptor_lines}\n"
        ")\n\n"
        "module_globals = globals()\n"
        "imported_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, module_globals)\n"
        "imported_builder.BuildTopDescriptorsAndMessages(\n"
        '    DESCRIPTOR, "engram.engram_pb2", module_globals\n'
        ")\n"
    )
    PROTOBUF_SOURCE.write_text(source, encoding="utf-8")


def remove_class(source: str, class_name: str) -> str:
    """Remove one generated experimental static-client class."""
    tree = parse(source, filename=str(GRPC_SOURCE))
    target = next((node for node in tree.body if isinstance(node, ClassDef) and node.name == class_name), ())
    if not target:
        return source
    lines = source.splitlines(keepends=True)
    start_line = int(target.lineno) - 1
    if start_line and "EXPERIMENTAL API" in lines[start_line - 1]:
        start_line -= 1
    end_line = int(target.end_lineno)
    while end_line < len(lines) and not lines[end_line].strip():
        end_line += 1
    result = "".join((*lines[:start_line], *lines[end_line:]))
    return result


def normalize_grpc_source() -> None:
    """Keep only the supported stub/servicer API and exact imports."""
    source = GRPC_SOURCE.read_text(encoding="utf-8")
    source = source.replace(
        "import grpc\nimport warnings\n",
        "from grpc import StatusCode as grpc_StatusCode\n"
        "from grpc import method_handlers_generic_handler as grpc_method_handlers_generic_handler\n"
        "from grpc import unary_unary_rpc_method_handler as grpc_unary_unary_rpc_method_handler\n",
    )
    source = source.replace("grpc.StatusCode", "grpc_StatusCode")
    source = source.replace("grpc.method_handlers_generic_handler", "grpc_method_handlers_generic_handler")
    source = source.replace("grpc.unary_unary_rpc_method_handler", "grpc_unary_unary_rpc_method_handler")
    source = source.replace("engram_dot_engram__pb2", "engram_protocol")
    source = source.replace("google_dot_protobuf_dot_empty__pb2", "protobuf_empty")
    source = source.replace("google_dot_protobuf_dot_struct__pb2", "protobuf_struct")
    source = source.replace("_registered_method=True", '**{"_registered_method": True}')
    runtime_guard_start = source.find("GRPC_GENERATED_VERSION =")
    first_stub = source.find("class EngramServiceStub:")
    if runtime_guard_start < 0 or first_stub < runtime_guard_start:
        raise ValueError("generated gRPC source has no removable runtime guard")
    source = source[:runtime_guard_start] + source[first_stub:]
    source = remove_class(source, "EngramService")
    source = remove_class(source, "EngramEvidenceService")
    GRPC_SOURCE.write_text(source, encoding="utf-8")


def regenerate() -> None:
    """Generate the current runtime modules and apply repository contracts."""
    command = (
        sys_executable,
        "-m",
        "grpc_tools.protoc",
        f"-I{REPOSITORY}",
        f"--python_out={REPOSITORY}",
        f"--grpc_python_out={REPOSITORY}",
        str(PROTO),
    )
    subprocess_run(command, check=True, cwd=REPOSITORY)
    normalize_protobuf_source()
    normalize_grpc_source()
    subprocess_run(
        (
            sys_executable,
            "-m",
            "black",
            "--quiet",
            str(PROTOBUF_SOURCE),
            str(GRPC_SOURCE),
        ),
        check=True,
        cwd=REPOSITORY,
    )
    if STALE_STUB.exists():
        STALE_STUB.unlink()


def main() -> int:
    """Regenerate protocol sources and report handled failures."""
    try:
        regenerate()
    except (CalledProcessError, OSError, SyntaxError, UnicodeError, ValueError) as error:
        print(f"protocol regeneration failed: {error}", file=stderr)
        return 1
    print("Engram protocol sources regenerated and normalized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
