# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from engram.v1 import engram_pb2 as engram_dot_v1_dot_engram__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engram/v1/engram_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngramServiceStub:
    """A single Engram process owns one instance of this service and one shared
    EngramCore. Conversation context is isolated by user_id; learned knowledge
    is shared by the core.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartConversation = channel.unary_unary(
                '/engram.v1.EngramService/StartConversation',
                request_serializer=engram_dot_v1_dot_engram__pb2.StartConversationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/engram.v1.EngramService/Chat',
                request_serializer=engram_dot_v1_dot_engram__pb2.ChatRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.InspectConversation = channel.unary_unary(
                '/engram.v1.EngramService/InspectConversation',
                request_serializer=engram_dot_v1_dot_engram__pb2.UserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.FinishConversation = channel.unary_unary(
                '/engram.v1.EngramService/FinishConversation',
                request_serializer=engram_dot_v1_dot_engram__pb2.UserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.StopConversation = channel.unary_unary(
                '/engram.v1.EngramService/StopConversation',
                request_serializer=engram_dot_v1_dot_engram__pb2.UserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.AddFact = channel.unary_unary(
                '/engram.v1.EngramService/AddFact',
                request_serializer=engram_dot_v1_dot_engram__pb2.AddFactRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.SetPredicate = channel.unary_unary(
                '/engram.v1.EngramService/SetPredicate',
                request_serializer=engram_dot_v1_dot_engram__pb2.SetPredicateRequest.SerializeToString,
                response_deserializer=engram_dot_v1_dot_engram__pb2.PredicateResponse.FromString,
                _registered_method=True)
        self.GetPredicate = channel.unary_unary(
                '/engram.v1.EngramService/GetPredicate',
                request_serializer=engram_dot_v1_dot_engram__pb2.GetPredicateRequest.SerializeToString,
                response_deserializer=engram_dot_v1_dot_engram__pb2.PredicateResponse.FromString,
                _registered_method=True)
        self.Propose = channel.unary_unary(
                '/engram.v1.EngramService/Propose',
                request_serializer=engram_dot_v1_dot_engram__pb2.ProposeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.Resolve = channel.unary_unary(
                '/engram.v1.EngramService/Resolve',
                request_serializer=engram_dot_v1_dot_engram__pb2.ResolveRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.LearnResponse = channel.unary_unary(
                '/engram.v1.EngramService/LearnResponse',
                request_serializer=engram_dot_v1_dot_engram__pb2.LearnResponseRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.RetireResponse = channel.unary_unary(
                '/engram.v1.EngramService/RetireResponse',
                request_serializer=engram_dot_v1_dot_engram__pb2.RetireResponseRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/engram.v1.EngramService/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.Flush = channel.unary_unary(
                '/engram.v1.EngramService/Flush',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=engram_dot_v1_dot_engram__pb2.FlushResponse.FromString,
                _registered_method=True)


class EngramServiceServicer:
    """A single Engram process owns one instance of this service and one shared
    EngramCore. Conversation context is isolated by user_id; learned knowledge
    is shared by the core.
    """

    def StartConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPredicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LearnResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetireResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Flush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngramServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartConversation,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.StartConversationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.ChatRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'InspectConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectConversation,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.UserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'FinishConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishConversation,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.UserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'StopConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.StopConversation,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.UserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'AddFact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFact,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.AddFactRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'SetPredicate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPredicate,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.SetPredicateRequest.FromString,
                    response_serializer=engram_dot_v1_dot_engram__pb2.PredicateResponse.SerializeToString,
            ),
            'GetPredicate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredicate,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.GetPredicateRequest.FromString,
                    response_serializer=engram_dot_v1_dot_engram__pb2.PredicateResponse.SerializeToString,
            ),
            'Propose': grpc.unary_unary_rpc_method_handler(
                    servicer.Propose,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.ProposeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.ResolveRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'LearnResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.LearnResponse,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.LearnResponseRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'RetireResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.RetireResponse,
                    request_deserializer=engram_dot_v1_dot_engram__pb2.RetireResponseRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=engram_dot_v1_dot_engram__pb2.FlushResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engram.v1.EngramService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engram.v1.EngramService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngramService:
    """A single Engram process owns one instance of this service and one shared
    EngramCore. Conversation context is isolated by user_id; learned knowledge
    is shared by the core.
    """

    @staticmethod
    def StartConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/StartConversation',
            engram_dot_v1_dot_engram__pb2.StartConversationRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/Chat',
            engram_dot_v1_dot_engram__pb2.ChatRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/InspectConversation',
            engram_dot_v1_dot_engram__pb2.UserRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/FinishConversation',
            engram_dot_v1_dot_engram__pb2.UserRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/StopConversation',
            engram_dot_v1_dot_engram__pb2.UserRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/AddFact',
            engram_dot_v1_dot_engram__pb2.AddFactRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPredicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/SetPredicate',
            engram_dot_v1_dot_engram__pb2.SetPredicateRequest.SerializeToString,
            engram_dot_v1_dot_engram__pb2.PredicateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPredicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/GetPredicate',
            engram_dot_v1_dot_engram__pb2.GetPredicateRequest.SerializeToString,
            engram_dot_v1_dot_engram__pb2.PredicateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/Propose',
            engram_dot_v1_dot_engram__pb2.ProposeRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/Resolve',
            engram_dot_v1_dot_engram__pb2.ResolveRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LearnResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/LearnResponse',
            engram_dot_v1_dot_engram__pb2.LearnResponseRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetireResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/RetireResponse',
            engram_dot_v1_dot_engram__pb2.RetireResponseRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v1.EngramService/Flush',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            engram_dot_v1_dot_engram__pb2.FlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
