# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from engram.v2 import engram_pb2 as engram_dot_v2_dot_engram__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engram/v2/engram_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngramEvidenceServiceStub:
    """The v2 service exposes transport-neutral unified resolution without changing
    the existing engram.v1 proposal-resolution service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveEvidence = channel.unary_unary(
                '/engram.v2.EngramEvidenceService/ResolveEvidence',
                request_serializer=engram_dot_v2_dot_engram__pb2.ResolveEvidenceRequest.SerializeToString,
                response_deserializer=engram_dot_v2_dot_engram__pb2.ResolutionResult.FromString,
                _registered_method=True)


class EngramEvidenceServiceServicer:
    """The v2 service exposes transport-neutral unified resolution without changing
    the existing engram.v1 proposal-resolution service.
    """

    def ResolveEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngramEvidenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveEvidence,
                    request_deserializer=engram_dot_v2_dot_engram__pb2.ResolveEvidenceRequest.FromString,
                    response_serializer=engram_dot_v2_dot_engram__pb2.ResolutionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engram.v2.EngramEvidenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engram.v2.EngramEvidenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngramEvidenceService:
    """The v2 service exposes transport-neutral unified resolution without changing
    the existing engram.v1 proposal-resolution service.
    """

    @staticmethod
    def ResolveEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engram.v2.EngramEvidenceService/ResolveEvidence',
            engram_dot_v2_dot_engram__pb2.ResolveEvidenceRequest.SerializeToString,
            engram_dot_v2_dot_engram__pb2.ResolutionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
